apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-shared
  annotations:
    storageclass.kubernetes.io/is-default-class: "true" 
provisioner: pxd.portworx.com
parameters:
  repl: "3"
  sharedv4: "true"
allowVolumeExpansion: true