apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  namespace: {{ .Values.namespace }}
  name: {{ include "ecr-renew.fullname" . }}
  labels:
    {{- include "ecr-renew.labels" . | nindent 4 }}
spec:
  encryptedData:
    ID: {{ .Values.aws.accessKeyId }}
    SECRET: {{ .Values.aws.secretKey }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: {{ include "ecr-renew.fullname" . }}
      namespace: {{ .Values.namespace }}

