---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins.aandd.io
  namespace: jenkins
spec:
  ingressClassName: kong
  rules:
  - host: jenkins.aandd.io
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: jenkins
            port:
              number: 8080