apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: longhorn-auth
  namespace: longhorn-system
config: 
  hide_credentials: true
plugin: basic-auth

---
apiVersion: v1
stringData:
  kongCredType: basic-auth
  username: admin
data:
  password: bWF0a2hhdWxvbmdob3Ju
kind: Secret
metadata:
  creationTimestamp: null
  name: longhorn-auth
  namespace: longhorn-system

---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: kong
username: longhorn
credentials:
- longhorn-auth

