apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semaphore
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: semaphore
  template:
    metadata:
      labels:
        app.kubernetes.io/name: semaphore
    spec:
      hostNetwork: true
      volumes:
        - name: semaphore-storage
          persistentVolumeClaim:
            claimName: semaphore-pvc
      containers:
        - name: mysql
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 65534
          image: "mysql:5.6"
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: semaphore
            - name: MYSQL_USER
              value: semaphore
            - name: MYSQL_PASSWORD
              value: semaphore
          ports:
            - name: http
              containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: semaphore-storage
        - name: semaphore
          securityContext:
            {}
          image: "ansiblesemaphore/semaphore:v2.8.53"
          imagePullPolicy: IfNotPresent
          env:
            - name: SEMAPHORE_DB_USER
              value: semaphore
            - name: SEMAPHORE_DB_PASS
              value: semaphore
            - name: SEMAPHORE_DB_HOST
              value: localhost
            - name: SEMAPHORE_DB_PORT
              value: "3306"
            - name: SEMAPHORE_DB
              value: semaphore
            - name: SEMAPHORE_PLAYBOOK_PATH
              value: /tmp/semaphore/
            - name: SEMAPHORE_ADMIN_PASSWORD
              value: cangetin
            - name: SEMAPHORE_ADMIN_NAME
              value: admin
            - name: SEMAPHORE_ADMIN_EMAIL
              value: admin@localhost
            - name: SEMAPHORE_ADMIN
              value: admin      
            - name: SEMAPHORE_ACCESS_KEY_ENCRYPTION
              value: YBpN8T5sM0vn6n2vHzjpuOvx+MWO+YQIv7/lor7q9VQ=              
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: semaphore-service
spec:
  selector:
    app.kubernetes.io/name: semaphore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000